### ISSUE TITLE
Server offline

### ISSUE THREAD

**Issue by jayvdb** [yanwarsolah/pybacor#1]
https://github.com/yanwarsolah/pybacor/blob/master/pybacor/api/config.py defines the BASE_URL as http://ibacor.com/api/ , and that is no longer working.

Is the server software available somewhere so it can be hosted?

**Comment by yanwarsolah** [comment]
I am currently looking. and the result ibacor in Indonesia is not supported anymore. So, this project I stop.

**Comment by jayvdb** [comment]
Can you please update PyPI to indicate the package is no longer functioning correctly.
And also update the GitHub repo description.

**Comment by yanwarsolah** [comment]
Ok, but not now, 
thanks @jayvdb already reminded me...
